## Import Libraries

In [ ]:
import numpy as np
import pandas as pd

## Load Data

In [ ]:
data = pd.read_csv("/content/Data-cleaning-for-beginners-using-pandas.csv")

In [ ]:
data.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
data.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

In [ ]:
data.shape

(29, 7)

In [ ]:
data.sample(4)

    Index   Age     Salary  Rating       Location  Established Easy Apply
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
8       8  35.0  $44k-$99k     5.4    New York,Ny           -1         -1
13     13  25.0  $44k-$99k    -1.0  Australia Aus         2019       TRUE

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

In [ ]:
data.isna().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [ ]:
data.columns

Index(['Index', 'Age', 'Salary', 'Rating', 'Location', 'Established',
       'Easy Apply'],
      dtype='object')

In [ ]:
data.columns = data.columns.str.lower().str.replace(' ','_')

In [ ]:
data.columns

Index(['index', 'age', 'salary', 'rating', 'location', 'established',
       'easy_apply'],
      dtype='object')

In [ ]:
data.head()

   index   age     salary  rating       location  established easy_apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [ ]:
avg_age = data.age.mean()

In [ ]:
data['age'] = data['age'].fillna(avg_age)
data['age'] = data['age'].round(decimals=1)
data['age']

0     44.0
1     66.0
2     39.0
3     64.0
4     25.0
5     44.0
6     21.0
7     44.0
8     35.0
9     22.0
10    55.0
11    44.0
12    39.0
13    25.0
14    66.0
15    44.0
16    19.0
17    39.0
18    35.0
19    32.0
20    39.0
21    35.0
22    19.0
23    39.0
24    13.0
25    55.0
26    39.0
27    52.0
28    39.0
Name: age, dtype: float64

In [ ]:
data['age'].isna().sum()

0

## Salary

In [ ]:
data['salary'] = data['salary'].apply(lambda x:x.replace('$',''))

In [ ]:
data.head()

   index   age   salary  rating       location  established easy_apply
0      0  44.0  44k-99k     5.4       India,In         1999       TRUE
1      1  66.0  55k-66k     3.5    New York,Ny         2002       TRUE
2      2  39.0  77k-89k    -1.0    New York,Ny           -1         -1
3      3  64.0  44k-99k     4.4       India In         1988         -1
4      4  25.0  44k-99k     6.4  Australia Aus         2002         -1

In [ ]:
data['salary']

0      44k-99k
1      55k-66k
2      77k-89k
3      44k-99k
4      44k-99k
5      77k-89k
6      44k-99k
7      44k-99k
8      44k-99k
9      44k-99k
10     10k-49k
11     10k-49k
12     44k-99k
13     44k-99k
14     44k-99k
15    88k-101k
16     19k-40k
17     44k-99k
18     44k-99k
19     44k-99k
20     44k-99k
21     44k-99k
22     55k-66k
23     44k-99k
24     44k-99k
25     44k-99k
26     55k-66k
27     44k-99k
28     39k-88k
Name: salary, dtype: object

In [ ]:
data['age'] = data['age'].astype(int)

## cleaning established column

In [ ]:
data["established"] = data["established"].replace(-1,np.nan)
data["established"].fillna('unknown', inplace=True)

## Location column

In [ ]:
data['location']

0          India,In
1       New York,Ny
2       New York,Ny
3          India In
4     Australia Aus
5          India,In
6       New York,Ny
7     Australia Aus
8       New York,Ny
9          India,In
10         India,In
11         India,In
12         India,In
13    Australia Aus
14    Australia Aus
15    Australia Aus
16         India,In
17      New York,Ny
18      New York,Ny
19      New York,Ny
20      New York,Ny
21      New York,Ny
22      New York,Ny
23      New York,Ny
24      New York,Ny
25    Australia Aus
26         India,In
27         India,In
28    Australia Aus
Name: location, dtype: object

In [ ]:
data['location'] = data['location'].str.replace("Australia Aus", "Australia,Aus")
data['location_city'] = data['location'].str.split(",", expand=True).get(0)
data['city_sign'] = data['location'].str.split(",", expand=True).get(1)
data.drop('location', inplace=True, axis=1)

In [ ]:
data.head()

   index  age   salary  rating established easy_apply location_city city_sign
0      0   44  44k-99k     5.4      1999.0       TRUE         India        In
1      1   66  55k-66k     3.5      2002.0       TRUE      New York        Ny
2      2   39  77k-89k    -1.0     unknown         -1      New York        Ny
3      3   64  44k-99k     4.4      1988.0         -1      India In      None
4      4   25  44k-99k     6.4      2002.0         -1     Australia       Aus

## Rating column

In [ ]:
data['rating'] = data["rating"].replace(-1,np.nan)

data['rating'] = data["rating"].fillna(data['rating'].mean()).round(decimals=1)

## Easy apply

In [ ]:
data['easy_apply'] = data['easy_apply'].replace("-1", "True")

## Salary column

In [ ]:
data['salary'].iloc[0]

data['salary'] = data['salary'].apply(lambda x:x.replace("$",''))
data['salary'] = data['salary'].apply(lambda x:x.replace("k", ''))

In [ ]:
data

    index  age  salary  rating established easy_apply location_city city_sign
0       0   44   44-99     5.4      1999.0       TRUE         India        In
1       1   66   55-66     3.5      2002.0       TRUE      New York        Ny
2       2   39   77-89     4.3     unknown       True      New York        Ny
3       3   64   44-99     4.4      1988.0       True      India In      None
4       4   25   44-99     6.4      2002.0       True     Australia       Aus
5       5   44   77-89     1.4      1999.0       TRUE         India        In
6       6   21   44-99     0.0     unknown       True      New York        Ny
7       7   44   44-99     4.3     unknown       True     Australia       Aus
8       8   35   44-99     5.4     unknown       True      New York        Ny
9       9   22   44-99     7.7     unknown       TRUE         India        In
10     10   55   10-49     5.4      2008.0       TRUE         India        In
11     11   44   10-49     6.7      2009.0       True         India        In
12     12   39   44-99     0.0      1999.0       True         India        In
13     13   25   44-99     4.3      2019.0       TRUE     Australia       Aus
14     14   66   44-99     4.0      2020.0       TRUE     Australia       Aus
15     15   44  88-101     3.0      1999.0       True     Australia       Aus
16     16   19   19-40     4.5      1984.0       True         India        In
17     17   39   44-99     5.3      1943.0       TRUE      New York        Ny
18     18   35   44-99     6.7      1954.0       TRUE      New York        Ny
19     19   32   44-99     3.3      1955.0       TRUE      New York        Ny
20     20   39   44-99     5.7      1944.0       TRUE      New York        Ny
21     21   35   44-99     5.0      1946.0       True      New York        Ny
22     22   19   55-66     7.8      1988.0       TRUE      New York        Ny
23     23   39   44-99     2.4      1999.0       TRUE      New York        Ny
24     24   13   44-99     4.3      1987.0       True      New York        Ny
25     25   55   44-99     0.0      1980.0       TRUE     Australia       Aus
26     26   39   55-66     4.3      1934.0       TRUE         India        In
27     27   52   44-99     5.4      1935.0       True         India        In
28     28   39   39-88     3.4      1932.0       True     Australia       Aus